[secfunc]
file_model = "model_data.txt"
nc = 10000

[forward]
file_model = "model_data.txt"
fmin = 1.0
fmax = 100.0
nf = 1000

[inversion]
#vs2model = "NearSurface"
vs2model = "FixVpRho"
model_ref = "mref.txt"

vs_width = 0.7
lambda = 1.0e-2
reg_type = 2

num_init = 100
num_noise = 1
#rand_depth = false
rand_depth = true
rand_vs = false
dintv_min = 0.001
nlayer = 10
zmax = 0.025

r0 = 0.5
rmin = 1.0
rmax = 1.5
#vs2vp = 3.0

weight = [4.0, 1.0, 1.0, 1.0]
